In [2]:
import torch

1. Buatlah sebuah tensor bernama `tensor_x` dengan menggunakan fungsi `torch.rand()` dengan ukuran 3x3. Kemudian cetak nilai dari `tensor_x` beserta tipe datanya dan dimensinya.

In [3]:
tensor_x = torch.rand(3, 3)
print(tensor_x)
print(tensor_x.dtype)
print(tensor_x.shape)

tensor([[0.0201, 0.4264, 0.7492],
        [0.2020, 0.3506, 0.1824],
        [0.4521, 0.2444, 0.1383]])
torch.float32
torch.Size([3, 3])


2. Buatlah sebuah tensor bernama `tensor_y` dengan menggunakan fungsi `torch.rand()` dengan ukuran 3x3. Kemudian cetak nilai dari `tensor_y` beserta nilai maksimum dan minimumnya.

In [4]:
tensor_y = torch.rand(3, 3)
print(tensor_y)
print(f"Max: {tensor_y.max()}")
print(f"Min: {tensor_y.min()}")

tensor([[0.5056, 0.3593, 0.8648],
        [0.8778, 0.9136, 0.9581],
        [0.6010, 0.3264, 0.2716]])
Max: 0.9581194519996643
Min: 0.27160149812698364


3. Lakukanlah operasi penjumlahan dan pengurangan antara `tensor_x` dan `tensor_y`. Simpan hasilnya pada variabel `tensor_sum` dan `tensor_sub`.

In [5]:
tensor_sum = tensor_x + tensor_y
print(tensor_sum)
tensor_sub = tensor_x - tensor_y
print(tensor_sub)

tensor([[0.5257, 0.7857, 1.6140],
        [1.0798, 1.2642, 1.1405],
        [1.0531, 0.5707, 0.4099]])
tensor([[-0.4855,  0.0671, -0.1157],
        [-0.6758, -0.5630, -0.7757],
        [-0.1489, -0.0820, -0.1333]])


4. Lakukan operasi perkalian matrix antara `tensor_x` dan `tensor_y`. Simpan hasilnya pada variabel `tensor_mul`. Lalu lakukan operasi transpose pada `tensor_mul`. Simpan hasilnya pada variabel `tensor_transpose`.

In [6]:
tensor_mul = torch.matmul(tensor_x, tensor_y)

# atau

tensor_mul = tensor_x @ tensor_y
print(tensor_mul)

tensor_transpose = tensor_mul.t()
print(tensor_transpose)

tensor([[0.8347, 0.6413, 0.6294],
        [0.5196, 0.4525, 0.5602],
        [0.5262, 0.4308, 0.6627]])


5. Ubah dimensi dari `tensor_transpose` menjadi 1x9 menggunakan reshape. Simpan hasilnya pada variabel `tensor_reshape`.

In [8]:
tensor_reshape = tensor_transpose.reshape(1, 9)
print(tensor_reshape)

tensor([[0.8347, 0.5196, 0.5262, 0.6413, 0.4525, 0.4308, 0.6294, 0.5602, 0.6627]])


6. Buat sebuah tensor random dengan random seed 42 bernama `tensor_random` dengan ukuran 3x3. Kemudian cetak nilai dari `tensor_random` beserta nilai maksimum dan minimumnya.

In [9]:
torch.manual_seed(42)
tensor_random = torch.rand(3, 3)
print(tensor_random)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])


7. Pindahkan `tensor_random` ke device GPU. Simpan hasilnya pada variabel `tensor_gpu`. Abaikan bagian ini jika anda tidak memiliki GPU

In [10]:
# move to gpu
if torch.cuda.is_available():
    device = torch.device("cuda")
    
tensor_random = tensor_random.to(device)