# Latihan Modul 01

## Pertanyaan 1
Buatlah sebuah data masukan berupa variabel x1, x2, dan x3, masing-masing sebanyak 100 elemen. Data tersebut berupa nilai integer 1 atau 0.

In [11]:
import torch
import torch.nn as nn

In [12]:
x1 = torch.randint(0, 2, (100,))
x2 = torch.randint(0, 2, (100,))
x3 = torch.randint(0, 2, (100,))

# print x1, x2, x3
print(f"x1:\n{x1}")
print(f"x2:\n{x2}")
print(f"x3:\n{x3}")

x1:
tensor([1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
        0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
        0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
        0, 0, 1, 1])
x2:
tensor([0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
        1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
        1, 0, 1, 0])
x3:
tensor([0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
        0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
        1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
        0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1

## Pertanyaan 2

Gabungkanlah data masukan dari x1, x2, dan x3 menggunakan fungsi `torch.stack()`. Ubahlah x menjadi tipe data float

In [13]:
x = torch.stack([x1, x2, x3], dim=1)
x = x.float()
print(f"x:\n{x}")

x:
tensor([[1., 0., 0.],
        [0., 1., 1.],
        [0., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 1., 0.],
        [1., 1., 0.],
        [1., 1., 0.],
        [0., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 1., 1.],
        [0., 1., 1.],
        [1., 1., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [1., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 0., 0.],
        [0., 1., 0.],
        [1., 0., 1.],
        [0., 1., 1.],
        [0., 1., 1.],
        [1., 1., 1.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 1., 1.],
        [1., 1., 0.],
        [0., 1., 1.],
        [0., 1., 0.],
       

## Pertanyaan 3

Buatlah sebuah _ground truth_ untuk operasi dari x1 XOR x2 NAND x3. Gunakan fungsi `torch.logical_xor()` dan `torch.logical_not()`. Konversikan hasilnya menjadi float

In [14]:
y = torch.logical_xor(x1, x2)
y = torch.logical_and(y, x3)
y = torch.logical_not(y).float()
print(f"y:\n{y}")

y:
tensor([1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1.,
        0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0.,
        1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1.,
        1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
        1., 0., 0., 1., 1., 0., 0., 1., 1., 1.])


## Pertanyaan 4

Lakukan split terhadap x dan y dengan persentase 80% untuk data training dan 20% untuk data testing.

In [15]:
train_length = int(0.8 * len(x))
x_train = x[:train_length]
y_train = y[:train_length]
x_test = x[train_length:]
y_test = y[train_length:]

print(f"Panjang dari x_train: {len(x_train)} | Panjang dari y_train: {len(y_train)} | Panjang dari x_test: {len(x_test)} | Panjang dari y_test: {len(y_test)}")

Panjang dari x_train: 80 | Panjang dari y_train: 80 | Panjang dari x_test: 20 | Panjang dari y_test: 20


## Pertanyaan 5

Buatlah model sederhana yang sama dengan model yang dibahas pada modul 01. Gunakan fungsi `nn.Linear()` untuk membuat model tersebut. Kamu dapat melakukan copy paste dari modul 01 namun jangan lupa untuk mengubah input dan output layer menjadi 3 yang tadinya 2

In [16]:
# membuat model regresi linear
class XORModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 3)
        self.sigmoid = nn.Sigmoid()
        self.linear2 = nn.Linear(3, 1)
        

    def forward(self, x):
        x = self.linear(x)
        x = self.sigmoid(x)
        x = self.linear2(x)
        x = self.sigmoid(x)
        return x

## Pertanyaan 6

Muat kelas model yang dibuat pada variabel `model` lalu gunakan fungsi `nn.CrossEntropyLoss()` untuk membuat fungsi loss dan `torch.optim.Adam()` untuk membuat optimizer dengan learning rate sebesar 0.1. 

In [17]:
model = XORModel()
loss_fn = nn.BCELoss()
optim = torch.optim.Adam(model.parameters(), lr=0.01)

## Pertanyaan 7

Buatlah training loop dengan epoch sebanyak 2000. Cetak loss setiap 100 epoch.

In [18]:
epoch = 2000
for i in range(epoch):
    y_pred = model(x_train)
    loss = loss_fn(y_pred, y_train.unsqueeze(1))
    optim.zero_grad()
    loss.backward()
    optim.step()

    # validasi
    with torch.no_grad():
        y_pred = model(x_test)
        val_loss = loss_fn(y_pred, y_test.unsqueeze(1))

    if i % 100 == 0:
        print(f"Epoch: {i} | Loss: {loss.item():.4f} | Val Loss: {val_loss.item():.4f}")


Epoch: 0 | Loss: 0.6452 | Val Loss: 0.6454
Epoch: 100 | Loss: 0.4109 | Val Loss: 0.4588
Epoch: 200 | Loss: 0.3352 | Val Loss: 0.4039
Epoch: 300 | Loss: 0.2785 | Val Loss: 0.3791
Epoch: 400 | Loss: 0.2387 | Val Loss: 0.3683
Epoch: 500 | Loss: 0.2072 | Val Loss: 0.3376
Epoch: 600 | Loss: 0.1560 | Val Loss: 0.2529
Epoch: 700 | Loss: 0.1054 | Val Loss: 0.1654
Epoch: 800 | Loss: 0.0714 | Val Loss: 0.1086
Epoch: 900 | Loss: 0.0511 | Val Loss: 0.0764
Epoch: 1000 | Loss: 0.0386 | Val Loss: 0.0571
Epoch: 1100 | Loss: 0.0303 | Val Loss: 0.0447
Epoch: 1200 | Loss: 0.0246 | Val Loss: 0.0361
Epoch: 1300 | Loss: 0.0204 | Val Loss: 0.0300
Epoch: 1400 | Loss: 0.0172 | Val Loss: 0.0253
Epoch: 1500 | Loss: 0.0148 | Val Loss: 0.0217
Epoch: 1600 | Loss: 0.0128 | Val Loss: 0.0189
Epoch: 1700 | Loss: 0.0112 | Val Loss: 0.0165
Epoch: 1800 | Loss: 0.0099 | Val Loss: 0.0146
Epoch: 1900 | Loss: 0.0088 | Val Loss: 0.0130


## Pertanyaan 8

Dengan menggunakan masukan berupa `[0, 0, 1]` dan `[1, 1, 0]` lakukan prediksi dengan model yang telah dibuat. Apakah hasilnya sudah tepat?

**Jawaban seharusnya**
- 0 XOR 0 NAND 1 = 1
- 1 XOR 1 NAND 0 = 1

In [19]:
x_inference = torch.tensor([[0, 0, 1], [1, 1, 0]], dtype=torch.float)
with torch.no_grad():
    y_pred = model(x_inference)
    y_pred = torch.round(y_pred).squeeze(1)
    print(f"y_pred:\n{y_pred}")

y_pred:
tensor([1., 1.])


In [22]:
y = torch.logical_xor(x_inference[:, 0], x_inference[:, 1])
y = torch.logical_and(y, x_inference[:, 2])
y = torch.logical_not(y).float()
print(y)

tensor([1., 1.])
