<a href="tba" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a> 

[Source Code Jupyter Notebook]()



# 0. Pengantar



Pada bagian ini kamu diharapkan mampu:
- Memahami esensi deep learning
- Memahami PyTorch dan alasan menggunakannya
- Membuat variabel tensor dan operasi tensor sederhana
- Menjalankan operasi tensor menggunakan GPU

<br>

<div align="center">
<img src="https://media.tenor.com/HWzTY5EBzOsAAAAC/are-you-ready-kids-sponge-bob.gif" width="350"/>
</div>


## Apa itu PyTorch

### Sekilas Tentang PyTorch

PyTorch adalah sebuah library Python yang digunakan untuk melakukan komputasi numerik dengan menggunakan GPU. PyTorch merupakan salah satu library yang paling populer untuk melakukan deep learning. PyTorch memiliki beberapa kelebihan dibandingkan dengan library deep learning lainnya, diantaranya:
- PyTorch memiliki API yang sangat mudah digunakan dan mudah dipelajari
- PyTorch memiliki dokumentasi yang lengkap dan mudah diakses
- PyTorch memiliki komunitas yang sangat besar dan aktif
- PyTorch memiliki dukungan dari perusahaan besar seperti Facebook, Uber, dan Google

Juga terdapat beberapa framework deep learning lainnya seperti TensorFlow, Keras, dan Caffe. Namun, pada tutorial ini kita akan menggunakan PyTorch sebagai framework utama untuk melakukan deep learning.

> Mana yeng lebih baik, PyTorch atau Tensorflow. Cari tahu jawabannya [pada tautan berikut ini](https://www.assemblyai.com/blog/pytorch-vs-tensorflow-in-2022/)

### Siapa saja yang menggunakan PyTorch
- [Facebook / MetaAI](https://ai.facebook.com/blog/pytorch-builds-the-future-of-ai-and-machine-learning-at-facebook/)
- [Uber](https://www.youtube.com/watch?v=i2hHC0NBY5s)
- [Tesla](https://analyticsindiamag.com/tesla-pytorch-self-driving-computer-vision-karpathy-elon-musk-ai/)
- [Microsoft](https://azure.microsoft.com/en-us/resources/developers/pytorch/#:~:text=PyTorch%20is%20an%20open%2Dsource,Bing%2C%20Xbox%2C%20and%20more.)
- [dan masih banyak lagi](https://analyticsindiamag.com/how-pytorch-is-increasingly-being-adopted-by-organizations/)

## Mulai menggunakan pytorch

Untuk mulai menggunakannya pastikan anda sudah melakukan instalasi sesuai dengan petunjuk [berikut ini](../instalasi) atau yang ada pada [website official PyTorch](https://pytorch.org/get-started/locally/)

### Mengimpor PyTorch

Setelah itu kamu dapat melakukan import library PyTorch dengan cara berikut:

In [2]:
import torch
print(torch.__version__)
print(f"Python version: {sys.version}")

1.13.0
Python version: 3.8.15 (default, Nov 24 2022, 15:19:38) 
[GCC 11.2.0]


Dalam tutorial ini, saya menggunakan PyTorch versi 1.13.0 dan Python versi 3.8.15. Versi kamu mungkin saja berbeda, namun itu tidak jadi masalah asalkan versi yang kamu gunakan adalah versi yang terbaru.

### Membuat Tensor

**Apa itu tensor?**

Tensor adalah sebuah array multidimensi yang dapat digunakan untuk melakukan operasi matematika. Tensor dapat digunakan untuk melakukan operasi matematika seperti perkalian matriks, konvolusi, dan lain-lain. Tensor juga dapat digunakan untuk melakukan operasi matematika pada data-data yang memiliki dimensi lebih dari 2.

<div align="center">

<img src="https://miro.medium.com/max/1144/1*PDC6NHVmFXFZqxFf4YRSDg.png" width="600"/>


</div>

_Sumber: [Analytics Vidhya](https://medium.com/analytics-vidhya/lighting-the-pytorch-tensors-298b82722420)_



**Mengapa operasi deep learning dilakukan pada tipe data tensor?**

Deep learning dilakukan pada tipe data tensor karena tensor memiliki struktur yang sesuai dengan cara kerja neural network. NN terdiri dari banyak node yang terhubung dengan satu sama lain, dan tensor dapat dengan mudah menyimulasikan hubungan antar node ini. Selain itu, tensor dibutuhkan ketika melakukan backpropagation, dimana kita perlu menghitung turunan dari fungsi loss terhadap parameter-parameter yang ada pada NN.

> **Catatan:**
> Jikalau sampai di tahap ini kamu bingung dengan penjelasannya, jangan khawatir. Kita akan membahasnya lebih dalam pada bagian selanjutnya. Biasanya setelah mencoba langsung, kamu akan lebih mudah memahami konsepnya.

Sekarang kita akan mencoba membuat tensor

In [3]:
# Tensor berbentuk skalar
scalar = torch.tensor(5)
print(scalar)

tensor(5)


Dalam hal ini, skalar maksudnya adalah sebuah bilangan tunggal, bukan sebuah array.

Kemudian, kita mencoba untuk membuat vektor, yaitu tensor dengan dimensi 1 yang memiliki beberapa elemen.

In [6]:
# vector
vector = torch.tensor([1, 2, 3, 4, 5])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([1, 2, 3, 4, 5])
1
torch.Size([5])


**Penjelasan**
- `torch.tensor()` digunakan untuk membuat tensor
- `print(vector.ndim)` digunakan untuk menampilkan dimensi dari tensor yang mana dimensi dari vektor adalah 1
- `print(vector.shape)` digunakan untuk menampilkan ukuran dari tensor yang mana ukuran dari vektor adalah 5, yang artinya vektor tersebut memiliki 5 elemen pada dimensi pertama

Mari lihat contoh lainnya:

In [7]:
# vector 2 dimensi
vector2 = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(vector2)
print(vector2.ndim)
print(vector2.shape)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
2
torch.Size([2, 5])


In [8]:
# vector 3 dimensi
vector3 = torch.tensor([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]])
print(vector3)
print(vector3.ndim)
print(vector3.shape)

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]])
3
torch.Size([2, 2, 5])


Dalam contoh vektor 3 dimensi, ukuran dari tensor adalah (2, 2, 5) yang artinya tensor tersebut memiliki 2 elemen pada dimensi pertama, 2 elemen pada dimensi kedua, dan 5 elemen pada dimensi ketiga.

Gambar berikut mungkin dapat memberikan gambaran yang lebih jelas tentang dimensi dan ukuran dari tensor.

<div align="center">
<img src="https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png" width="600"/>



</div>

_Sumber: [Mrdbourke's Github](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)_

### Membuat Random Tensor

Kita juga dapat membuat tensor dengan nilai random. Kita dapat melakukan hal ini dengan menggunakan fungsi `torch.rand()`. Fungsi ini akan menghasilkan nilai random dengan distribusi uniform.

Misalnya:

In [10]:
# Random Tensor Dengan Ukuran (4,5)
randomtensor = torch.rand(4, 5)
print(randomtensor)
print(randomtensor.ndim)
print(randomtensor.shape)

tensor([[0.1194, 0.6133, 0.7105, 0.1851, 0.7984],
        [0.4052, 0.5658, 0.0851, 0.3112, 0.5106],
        [0.2376, 0.1833, 0.8114, 0.8657, 0.7385],
        [0.8214, 0.4312, 0.4721, 0.3701, 0.4834]])
2
torch.Size([4, 5])


contoh lainnya:

In [11]:
# Random Tensor dengan ukuran (2,3,4)
randomtensor2 = torch.rand(2, 3, 4)
print(randomtensor2)
print(randomtensor2.ndim)
print(randomtensor2.shape)

tensor([[[0.8646, 0.5219, 0.5577, 0.9573],
         [0.0956, 0.4181, 0.6809, 0.3668],
         [0.0375, 0.4865, 0.7610, 0.3619]],

        [[0.6733, 0.8181, 0.1216, 0.5344],
         [0.8392, 0.0322, 0.5567, 0.8987],
         [0.1189, 0.4480, 0.6800, 0.8708]]])
3
torch.Size([2, 3, 4])


### Membuat Range Tensor

Kita juga dapat membuat tensor dengan nilai range. Kita dapat melakukan hal ini dengan menggunakan fungsi `torch.arange()`. Fungsi ini akan menghasilkan nilai range dengan interval yang ditentukan.

Contohnya:

In [12]:
# Range Tensor
rangetensor = torch.arange(0, 10)
print(rangetensor)
print(rangetensor.ndim)
print(rangetensor.shape)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
1
torch.Size([10])


**Penjelasan**

- `torch.arange()` digunakan untuk membuat tensor dengan nilai range
- Argumen pertama dari fungsi `torch.arange()` adalah nilai awal dari range, yaitu 0
- Argumen kedua dari fungsi `torch.arange()` adalah nilai akhir dari range, yaitu 10

In [13]:
# Contoh lain range tensor
rangetensor2 = torch.arange(0, 10, 2)
print(rangetensor2)
print(rangetensor2.ndim)
print(rangetensor2.shape)

tensor([0, 2, 4, 6, 8])
1
torch.Size([5])


**Penjelasan**
- Argumen ketiga dari fungsi `torch.arange()` adalah interval dari range, yaitu 2
- Dalam hal ini, kita akan mendapatkan nilai range dari 0 sampai 10 dengan interval 2

In [14]:
# Contoh lain range tensor
rangetensor3 = torch.arange(0, 10, 0.5)
print(rangetensor3)
print(rangetensor3.ndim)
print(rangetensor3.shape)

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000, 5.0000, 5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000,
        9.0000, 9.5000])
1
torch.Size([20])


### Tensor Zeros dan Ones

Zeros adalah tensor yang berisi semua nilai 0, sedangkan ones adalah tensor yang berisi semua nilai 1. Kita dapat membuat tensor zeros dan ones dengan menggunakan fungsi `torch.zeros()` dan `torch.ones()`.

Contohnya:

In [15]:
# Tensor dengan nilai 1
tensor1 = torch.ones(4, 5)
print(tensor1)
print(tensor1.ndim)
print(tensor1.shape)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
2
torch.Size([4, 5])


In [16]:
# Tensor dengan nilai 0
tensor0 = torch.zeros(4, 5)
print(tensor0)
print(tensor0.ndim)
print(tensor0.shape)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
2
torch.Size([4, 5])


### Mengecek dan Mengubah Tipe Data Tensor
Untuk mengecek tipe data dari tensor, kita dapat menggunakan fungsi `dtype` dari tensor tersebut. Untuk mengubah tipe data dari tensor, kita dapat menggunakan fungsi `to()` dari tensor tersebut. Contohnya sebagai berikut:

In [17]:
tensor_x = torch.arange(0, 5)
print(tensor_x)
print(tensor_x.ndim)
print(tensor_x.shape)
print(tensor_x.dtype)

tensor([0, 1, 2, 3, 4])
1
torch.Size([5])
torch.int64


Dalam contoh di atas, kita menggunakan fungsi `dtype` untuk mengecek tipe data dari tensor `x`. Kemudian, kita menggunakan fungsi `to()` untuk mengubah tipe data dari tensor `x` menjadi `float32` pada contoh berikut ini:

In [18]:
# konversi tensor_x menjadi float32
tensor_x = tensor_x.float()
print(tensor_x.dtype)

torch.float32


Kita juga dapat mendefinisikan tipe data dari tensor di awal ketika kita membuat tensor tersebut. Contohnya sebagai berikut:

In [19]:
tensor_x = torch.arange(0, 5).float()
print(tensor_x.dtype)

torch.float32


Terdapat banyak tipe data pada PyTorch. Pada umumnya, kita akan menggunakan `float32` atau torch.float. Ini mengacu pada bilangan real dengan presisi 32-bit. Untuk melihat daftar lengkap dari tipe data yang tersedia, kamu dapat membuka dokumentasi PyTorch [disini](https://pytorch.org/docs/stable/tensors.html).

**Apa itu Presisi 32-bit?**

Presisi 32-bit adalah jumlah bit yang digunakan untuk menyimpan bilangan real. Semakin banyak bit yang digunakan, semakin presisi bilangan real yang dapat disimpan. Semakin presisi bilangan real yang dapat disimpan, semakin besar ukuran dari bilangan real tersebut.

**Apakah bisa menggunakan tipe data lain?**

Tentu saja bisa. Terdapat istilah half-precision dan double-precision. Half-precision adalah tipe data dengan presisi 16-bit, sedangkan double-precision adalah tipe data dengan presisi 64-bit.

**Mengapa Menggunakan Float dan Bukan Integer?**

Karena kita akan melakukan operasi matematika pada tensor, maka kita membutuhkan tipe data yang dapat menyimpan bilangan real. Operasi matematika ini akan menghasilkan bilangan real, bukan bilangan bulat. Semakin presisi bilangan real yang dapat disimpan, semakin presisi hasil dari operasi matematika tersebut. Namun, semakin presisi bilangan real yang dapat disimpan, semakin besar ukuran dari bilangan real tersebut.



<div align="center">

<img src="https://blogs.nvidia.com/wp-content/uploads/2020/05/tf32-Mantissa-chart-hi-res-FINAL.png" width=600>

</div>

_Sumber: [Nvidia Blog](https://blogs.nvidia.com/blog/2020/05/14/tensorfloat-32-precision-format/)_