In [1]:
import torch
from torch import nn
import pytorch_lightning as pl

In [2]:
# membuat variabel x berisi nilai boleean berisi 1 atau 0 sebanyak 50 elemen
x1 = torch.randint(0, 2, (50,))
x2 = torch.randint(0, 2, (50,))
print(f"Input X1:\n{x1}")
print(f"Input X2:\n{x2}")

Input X1:
tensor([0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
        1, 0])
Input X2:
tensor([0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
        0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
        1, 0])


In [3]:
# menggabungkan variabel x1 dan x2 menjadi satu variabel x
x = torch.stack((x1, x2), dim=1)
print(x)

tensor([[0, 0],
        [1, 1],
        [1, 0],
        [0, 0],
        [1, 1],
        [1, 1],
        [0, 1],
        [0, 0],
        [1, 0],
        [0, 0],
        [1, 0],
        [0, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [0, 1],
        [1, 1],
        [1, 0],
        [1, 1],
        [0, 1],
        [1, 0],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 1],
        [0, 0],
        [0, 1],
        [1, 1],
        [1, 0],
        [1, 0],
        [1, 1],
        [1, 1],
        [0, 0],
        [1, 1],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 0],
        [1, 1],
        [0, 1],
        [1, 1],
        [0, 0],
        [1, 1],
        [0, 0]])


In [4]:
# membuat ground-truth dari input x1 dan x2 yang sudah distack pada x
y = x[:, 0] ^ x[:, 1]
print(f"Ground-truth Y:\n{y}")

Ground-truth Y:
tensor([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
        1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
        0, 0])


In [5]:
train_split = int(0.8*len(x))

In [6]:
# membagi x menjadi train dan testing
x_train = x[:train_split]
x_test = x[train_split:]

# membagi y menjadi train dan testing
y_train = y[:train_split]
y_test = y[train_split:]

In [7]:
# membuat model regresi linear
class XORModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2, 2)
        self.sigmoid = nn.Sigmoid()
        self.linear2 = nn.Linear(2, 1)
        

    def forward(self, x):
        x = x.float()
        x = self.linear(x)
        x = self.sigmoid(x)
        x = self.linear2(x)
        x = self.sigmoid(x)
        return x

In [8]:
# # membuat model regresi linear
# class XORModel2(pl.LightningModule):
#     def __init__(self):
#         super().__init__()
#         self.linear = nn.Linear(2, 2)
#         self.sigmoid = nn.Sigmoid()
#         self.linear2 = nn.Linear(2, 1)
#         self.loss_fn = nn.MSELoss()

#     def forward(self, x):
#         x = x.float()
#         x = self.linear(x)
#         x = self.sigmoid(x)
#         x = self.linear2(x)
#         x = self.sigmoid(x)
#         return x

#     def configure_optimizers(self):
#         return torch.optim.SGD(self.parameters(), lr=0.1, momentum=0.9)
    
#     def training_step(self, batch, batch_idx):
#         x, y = batch
#         y_hat = self(x)
#         loss = self.loss_fn(y_hat, y.unsqueeze(1).float())
#         self.log('train_loss', loss)
#         return loss


In [9]:
# # trainer
# trainer = pl.Trainer(
#     max_epochs=1000,
#     track_grad_norm=2,
#     accelerator='gpu',
#     devices=1,
#     log_every_n_steps=1,
# )

# # membuat model
# model = XORModel2()

# # membuat dataloader
# train_loader = torch.utils.data.DataLoader(
#     torch.utils.data.TensorDataset(x_train, y_train),
#     batch_size=50,
#     shuffle=True,
# )

# # training
# trainer.fit(model, train_loader)

In [10]:
# create instance
model = XORModel()

# check state_dict
print(model.state_dict())

OrderedDict([('linear.weight', tensor([[ 0.3842, -0.1170],
        [ 0.5053,  0.0350]])), ('linear.bias', tensor([-0.2968,  0.1043])), ('linear2.weight', tensor([[-0.5254,  0.3724]])), ('linear2.bias', tensor([0.1998]))])


In [11]:
# mencoba inferensi dengan input x
y_pred = model(x_test)
print(f"Input:\n{x_test}")
print(f"Hasil prediksi:\n{y_pred}")
print(f"Ground-truth:\n{y_test}")

Input:
tensor([[1, 0],
        [0, 1],
        [1, 0],
        [0, 0],
        [1, 1],
        [0, 1],
        [1, 1],
        [0, 0],
        [1, 1],
        [0, 0]])
Hasil prediksi:
tensor([[0.5416],
        [0.5473],
        [0.5416],
        [0.5428],
        [0.5462],
        [0.5473],
        [0.5462],
        [0.5428],
        [0.5462],
        [0.5428]], grad_fn=<SigmoidBackward0>)
Ground-truth:
tensor([1, 1, 1, 0, 0, 1, 0, 0, 0, 0])


In [12]:
print(f"Shape yPred: {y_pred.shape}")

Shape yPred: torch.Size([10, 1])


In [13]:
# mendefinisikan loss function
loss_fn = nn.MSELoss()

# optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=0.1, momentum=0.9)

# epoch
epochs = 10000

train_loss_list = []
test_loss_list = []
epoch_count = []

In [14]:
# training loop
for epoch in range(epochs):
    # training
    y_pred = model(x_train)
    y_train = y_train.float()
    loss = loss_fn(y_pred, y_train.unsqueeze(1))

    # backward
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    # testing
    with torch.no_grad():
        y_test_pred = model(x_test)
        y_test = y_test.float()
        test_loss = loss_fn(y_test_pred, y_test.unsqueeze(1))

    # print loss only 3 digit after comma. Log every 500 epoch
    if (epoch+1) % 50 == 0:
        print(f"Epoch: {epoch+1}, Loss: {loss.item():.3f}, Test Loss: {test_loss.item():.3f}")

    # append loss
    train_loss_list.append(loss.item())
    test_loss_list.append(test_loss.item())
    epoch_count.append(epoch+1)

Epoch: 50, Loss: 0.240, Test Loss: 0.240
Epoch: 100, Loss: 0.240, Test Loss: 0.240
Epoch: 150, Loss: 0.239, Test Loss: 0.240
Epoch: 200, Loss: 0.239, Test Loss: 0.240
Epoch: 250, Loss: 0.239, Test Loss: 0.240
Epoch: 300, Loss: 0.238, Test Loss: 0.240
Epoch: 350, Loss: 0.238, Test Loss: 0.241
Epoch: 400, Loss: 0.237, Test Loss: 0.241
Epoch: 450, Loss: 0.237, Test Loss: 0.241
Epoch: 500, Loss: 0.236, Test Loss: 0.241
Epoch: 550, Loss: 0.236, Test Loss: 0.242
Epoch: 600, Loss: 0.235, Test Loss: 0.242
Epoch: 650, Loss: 0.235, Test Loss: 0.243
Epoch: 700, Loss: 0.235, Test Loss: 0.243
Epoch: 750, Loss: 0.235, Test Loss: 0.244
Epoch: 800, Loss: 0.234, Test Loss: 0.244
Epoch: 850, Loss: 0.234, Test Loss: 0.244
Epoch: 900, Loss: 0.234, Test Loss: 0.244
Epoch: 950, Loss: 0.233, Test Loss: 0.244
Epoch: 1000, Loss: 0.232, Test Loss: 0.243
Epoch: 1050, Loss: 0.231, Test Loss: 0.242
Epoch: 1100, Loss: 0.227, Test Loss: 0.239
Epoch: 1150, Loss: 0.222, Test Loss: 0.234
Epoch: 1200, Loss: 0.212, Test 

In [15]:
# mencoba inferensi dengan input yang diberikan pengguna
x_user = torch.tensor([[1, 1]])
y_truth = x_user[:, 0] ^ x_user[:, 1]
y_pred = model(x_user)

print(f"Input:\n{x_user}")
print(f"Hasil prediksi:\n{y_pred}")
print(f"Ground-truth:\n{y_truth}")

Input:
tensor([[1, 1]])
Hasil prediksi:
tensor([[0.0146]], grad_fn=<SigmoidBackward0>)
Ground-truth:
tensor([0])
